### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' 

### ISSUE THREAD

**Issue by aetonsi** [xpl/get-source#4]
Hello,
i'm using [xpl/stacktracey](https://github.com/xpl/stacktracey) in a [framework7](https://github.com/framework7io/framework7) project with webpack which targets `web` or `cordova`.
After `npm install`ing stacktracey and running webpack dev server with target `web`, the following error is reported:

```log
ERROR in a:/projects/temp/node_modules/get-source/get-source.js
Module not found: Error: Can't resolve 'fs' in 'a:\projects\temp\node_modules\get-source'
 @ a:/projects/temp/node_modules/get-source/get-source.js 144:41-62 156:40-61
 @ a:/projects/temp/node_modules/stacktracey/stacktracey.js
 @ a:/projects/temp/src/js/errorReporter.js
 @ a:/projects/temp/src/js/app.js
 @ multi ./src/js/app.js
i ｢wdm｣: Failed to compile.
```

Apparently `isBrowser` is **false** so the `if`s on lines 138 and 152 go into the non-browser branch... Is this correct?

<hr>

Have a nice day

**Comment by wycats** [comment]
I hit the same issue with webpack.

**Comment by xpl** [comment]
> Is this correct?

I think that happens when compiling, not when running the script, so it's not about `isBrowser`. It's webpack being too smart and trying to resolve `module.require('fs')` to an import (which doesn't exist in non-node environment). Could you please make a minimal error repro and upload it to GitHub?

I don't know but maybe if we assign `module.require` to a variable like `const _require = module.require` and then use `_require('fs')` it will do the trick... The trick is to obfuscate the `require` so that Webpack couldn't recognize it and thus doesn't try to resolve it in compile-time. Previously, `module.require` worked, but now it doesn't seem to be the case anymore?..

**Comment by wycats** [comment]
@xpl at minimum, you should probably point people to https://webpack.js.org/configuration/node/ and tell them to configure webpack to configure `fs` and `path` with `"empty"` or `false`.

**Comment by aetonsi** [comment]
> @xpl at minimum, you should probably point people to https://webpack.js.org/configuration/node/ and tell them to configure webpack to configure `fs` and `path` with `"empty"` or `false`.

Hi, i tried adding this (`node: {fs: "empty"}`) or `externals: {fs: "commonjs fs"}` ([doc here](https://webpack.js.org/configuration/externals/#externals)) and they both seem to work. I'm not sure about any possible side effect on other node modules, though...

@xpl yeah it seems to be a compilation issue, because with said workarounds it seems to be compiling.
Anyway here's a minimal setup: https://github.com/aetonsi/get-source-error-webpack-demo/
I left the workaround commented in `webpack.config.js` so you can toggle that line if you want to try it

**Comment by xpl** [comment]
> Anyway here's a minimal setup

Thank you, I'll play around with that.

**Comment by xpl** [comment]
> and tell them to configure webpack to configure fs and path with "empty" or false.

@wycats Yeah, I'll try to make a zero-configuration fix first (today), and if that doesn't work, I'll add the said workaround to the README.

**Comment by wycats** [comment]
@xpl how do you feel about adding a test and having regular CI tests against webpack latest so we can catch this kind of bug more systematically?

**Comment by aetonsi** [comment]
> > and tell them to configure webpack to configure fs and path with "empty" or false.
> 
> @wycats Yeah, I'll try to make a zero-configuration fix first (today), and if that doesn't work, I'll add the said workaround to the README.

As far as you know, may these workarounds have any side effects?

I simply applied them after quickly reading the docs, but i have absolutely no clue about what the repercussions on other packages may be...

**Comment by xpl** [comment]
I have managed to fool WebPack with:

```js
nodeRequire = isBrowser ? null : module.require
```

and then

```js
nodeRequire ('fs')
```

Thanks @aetonsi for setting up the minimal repro case, it greatly speeded up the fix :)

**Comment by xpl** [comment]
> how do you feel about adding a test and having regular CI tests against webpack latest so we can catch this kind of bug more systematically?

@wycats It's a great idea, I'll try to wrap it up in a test.

**Comment by xpl** [comment]
@aetonsi I have updated stacktracey to 2.0.13. Could you please check if it works in your project without the need to change the config?

**Comment by aetonsi** [comment]
> @aetonsi I have updated stacktracey to 2.0.13. Could you please check if it works in your project without the need to change the config?

The 2.0.13 update solves the problem without changing config, thanks!

Let me know if i can delete the webpack demo repo, or if you still need it for the test.

Have a nice day.

**Comment by xpl** [comment]
> Let me know if i can delete the webpack demo repo, or if you still need it for the test.

Feel free to delete it, it has served its purpose :)
